package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.TextArea;

public class EarthquakeDataController {
	@FXML
	private Button help;
	@FXML
	private Button summary;
	@FXML
	private Button print;
	@FXML
	private Button printby;
	@FXML
	private Button search;
	@FXML
	private TextArea textArea;
	@FXML
	private Label textLabel;
	@FXML
	private Label title;

	// Event Listener on Button[#help].onAction
	@FXML
	public void helpButtonClick(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#summary].onAction
	@FXML
	public void summaryButtonClick(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#print].onAction
	@FXML
	public void printButtonClick(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#printby].onAction
	@FXML
	public void printByButtonClick(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#search].onAction
	@FXML
	public void searchButtonClick(ActionEvent event) {
		// TODO Autogenerated
	}
}
