package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.TextArea;

public class EarthquakeDataController {
	@FXML
	private Button help;
	@FXML
	private Button summary;
	@FXML
	private Button print;
	@FXML
	private Button printby;
	@FXML
	private Button search;
	@FXML
	private TextArea textArea;
	@FXML
	private Label textLabel;
	@FXML
	private Label title;

	// Event Listener on Button[#help].onAction
	@FXML
	public void helpButtonClick(ActionEvent event) {
		textArea.setText("Sumarry Button: print out a summary of all of the data (# of events, timerange of the events,etc) Click on button to invoke." + "/n" + 
				"Print Button: Prints out all the earthquake events. Click on button to invoke." + "/n" + "Print By Button: Print out all the Earthquake events, sorted by some field (date, depth, mag, place, status) Click on button, then set field to sort by."
				+ "/n" + "Search Button: Print out all of the earthquake events that meet some criteria (date, location, depth, mag, magType, place, status). Click on button, then set field to search." 
				+ "/n" + "Help Button: Prints out the description of buttons and how to invoke them. Click on button to invoke."
				);
	}
	// Event Listener on Button[#summary].onAction
	@FXML
	public void summaryButtonClick(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#print].onAction
	@FXML
	public void printButtonClick(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#printby].onAction
	@FXML
	public void printByButtonClick(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#search].onAction
	@FXML
	public void searchButtonClick(ActionEvent event) {
		// TODO Autogenerated
	}
}
