package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class fileSaveWindowController {
	@FXML
	private Button saveButton;
	@FXML
	private Button cancelButton;
	@FXML
	private TextField fileNameField;

	// Event Listener on Button[#saveButton].onAction
	@FXML
	public void saveButtonAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#cancelButton].onAction
	@FXML
	public void cancelButtonAction(ActionEvent event) {
		// TODO Autogenerated
	}
}
