package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class helpWindowController {
	@FXML
	private Button closeButton;
	@FXML
	private Label helpTextLabel;

	// Event Listener on Button[#closeButton].onAction
	@FXML
	public void closeButtonAction(ActionEvent event) {
		// TODO Autogenerated
	}
}
