package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.TextArea;

import javafx.scene.control.ChoiceBox;

public class MainController {
	@FXML
	private Button help;
	@FXML
	private Button dataSummary;
	@FXML
	private TextArea output;
	@FXML
	private Button allEvents;
	@FXML
	private Button Search;
	@FXML
	private ChoiceBox<String> searchDrop;
	@FXML
	private TextField searchText;
	@FXML
	private TextField searchText2;
	

	// Event Listener on Button[#help].onAction
	@FXML
	public void helpAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#dataSummary].onAction
	@FXML
	public void dataSummaryAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#allEvents].onAction
	@FXML
	public void allEventsAction(ActionEvent event) {
        //prints all earthquake objects
		
	}
	// Event Listener on Button[#Search].onAction
	@FXML
	public void searchByAction(ActionEvent event) {
		// TODO Autogenerated
	}
	
	//@FXML
	//public void initialize() {
	//    printByDrop.getItems().removeAll(printByDrop.getItems());
	//    printByDrop.getItems().addAll("time", "latitude", "longitude", "depth",
	//    		"magnitude", "magnitude type", "NST", "Gap", "dMin", 
	//    		"rms", "net", "id", "updated", "place", "type", 
	//    		"horizontal error", "depth error", "magnitude error", 
	//    		"magnitude NST", "status", "location source", "magnitude source");
	//    printByDrop.getSelectionModel().select("magnitude");
	//}
}
